### ISSUE TITLE
ImNDT / OpenVR SDK 2.15.6 / Visual C++ Build errors

### ISSUE THREAD

**Issue by codeling** [3dct/open_iA#77]
When trying to build with openvr 2.15.6 on Visual Studio 2026 (18.4.3), there's a lot of build errors in ImNDT module, like this

```
C:\sb\openvr-2.15.6\headers\openvr.h(2905,70): error C3927: '->': trailing return type is not allowed after a non-function declarator [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,70): error C3613: missing return type after '->' ('int' assumed) [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,70): error C2146: syntax error: missing ')' before identifier 'SetSDKVersion' [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,70): error C3646: 'SetSDKVersion': unknown override specifier [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,23): error C2059: syntax error: '(' [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,70): error C2059: syntax error: '(' [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,79): error C2059: syntax error: '=' [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)

C:\sb\openvr-2.15.6\headers\openvr.h(2905,82): error C2238: unexpected token(s) preceding ';' [C:\sb\open_iA\bin\modules\ImNDT.vcxproj]
    (Quelldatei "../../src/modules/ImNDT/iAvtkVR.cpp" wird kompiliert)
```

These errors do not appear with 2.12.14 or any tested version prior.

There is no trailing return type specification on the lines suggested by the error messages, so its unclear how the error actually comes to pass, maybe a stray `#define`
